title: Blogfolio of Fredrik
author: Fredrik Johansson
email: longchank@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A portfolio / blog where I show off the stuff I have done in my past and blogging about the present.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Fredrik Johansson
  tagline: Developer. 3D Artist
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: Portfolio
      url: "/work"
    - title: About
      url: "/about"
  # generate social links in footer
  social_links:
    # twitter: thelehhman
    # github:  thelehhman
    linkedIn: in/fredrik-johansson-b4637221/
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - work.md
collections_dir: collections
collections:
  portfolio:
    output: true
  - posts
# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
